apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - name: http
          containerPort: 8123
        - name: tcp
          containerPort: 9000
        volumeMounts:
        - name: user-config
          mountPath: /etc/clickhouse-server/users.d/default-user.xml
          subPath: default-user.xml
      volumes:
      - name: user-config
        configMap:
          name: clickhouse-user-config
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
  - name: http
    protocol: TCP
    port: 8123
    targetPort: 8123
  - name: tcp
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP
